export const USER_REGISTRATION = 'USER_REGISTRATION';
export const USER_REGISTERED = 'USER_REGISTERED';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const SET_CHAT_STATE = 'SET_CHAT_STATE';

